banner_short: "ผู้ช่วยสุขภาพ Aid-gent ให้ข้อมูลทั่วไปและช่วยสรุปอาการ (ไม่ใช่การวินิจฉัย/สั่งยา) หากฉุกเฉิน โทร 1669 หรือไป ER ทันที"
emergency_main: "อาการของคุณเข้าข่ายฉุกเฉิน แนะนำโทร 1669 หรือไป ER ใกล้คุณทันทีค่ะ เพื่อความปลอดภัย ฉันจะหยุดให้คำแนะนำเพิ่มเติมตอนนี้"
emergency_short: "อาการเข้าเกณฑ์ฉุกเฉินค่ะ โทร 1669 หรือไป ER ใกล้คุณทันที ฉันจะหยุดให้คำแนะนำต่อ"
emergency_voice: "ขณะนี้อาการเข้าข่ายฉุกเฉิน โปรดโทรหนึ่งหกหกเก้า หรือไปห้องฉุกเฉินที่ใกล้ที่สุดทันที เพื่อความปลอดภัย ฉันจะหยุดให้คำแนะนำเพิ่มเติม"
emergency_persist: "ฉันกังวลเรื่องความปลอดภัยของคุณจริง ๆ ค่ะ อาการที่บอกมาจัดเป็นฉุกเฉินและอาจอันตรายได้ แนะนำโทร 1669 หรือไป ER ใกล้คุณทันที"
footer_safety: "ฉันให้ข้อมูลทั่วไปเพื่อการดูแลเบื้องต้นเท่านั้น ไม่ใช่การวินิจฉัยหรือสั่งยา หากกังวลหรืออาการไม่ดีขึ้น โปรดปรึกษาแพทย์ค่ะ"
not_enough_data: "ยังไม่มีข้อมูลเพียงพอจากเอกสารของคลินิกที่จะตอบได้อย่างมั่นใจค่ะ"
rag_timeout: "ขณะนี้ไม่สามารถเข้าถึงเอกสารอ้างอิงได้ ลองอีกครั้งภายหลังนะคะ"
llm_timeout: "ระบบตอบช้ากว่าปกติ ลองพิมพ์ซ้ำอีกครั้งได้ค่ะ"
