version: 0.1
resp_upper:
  main_symptoms: "ตอนนี้อาการหลักมีอะไรบ้างคะ (เช่น ไข้/ไอ/เจ็บคอ/น้ำมูก)?"
  duration: "เริ่มมีอาการมานานแค่ไหนแล้วคะ (เช่น 2 วัน/36 ชั่วโมง)?"
  fever_measured: "ได้วัดอุณหภูมิหรือยังคะ (ตอบ ได้/ไม่ได้)?"
  fever_max_c: "วัดไข้สูงสุดได้กี่องศาเซลเซียสคะ? (ถ้าไม่ได้วัด พิมพ์ 'ไม่ทราบ' ได้ค่ะ)"
  fever_method: "วัดไข้จากบริเวณไหนคะ (รักแร้/ปาก/หู/หน้าผาก)? (ถ้าไม่ได้วัด พิมพ์ 'ไม่ทราบ')"
  severity_overall: "ความรุนแรงโดยรวมตอนนี้อยู่ระดับไหนคะ (เล็กน้อย/ปานกลาง/มาก)?"
  co_symptoms: "มีอาการร่วม: หายใจลำบาก/กลืนลำบาก/ผื่น/ปวดหู/เสียงแหบ หรือไม่คะ (ระบุเป็นข้อ ๆ ว่ามี/ไม่มี)?"
  risk_factors: "มีปัจจัยเสี่ยงไหมคะ (ตั้งครรภ์/โรคประจำตัวสำคัญ เช่น หอบหืด เบาหวาน ความดัน/ผู้สูงอายุ)?"
  meds_allergies: "ตอนนี้มียาที่ใช้อยู่หรือมีประวัติแพ้ยาหรือไม่คะ?"
  exposures_optional: "มีคนใกล้ชิดป่วยหรือเพิ่งเดินทางต่างจังหวัด/ต่างประเทศไหมคะ?"
derm_rash:
  rash_morphology: "ผื่นมีลักษณะอย่างไรคะ (แดง/นูน/แห้งลอก/ตุ่มน้ำ/เป็นวง/ลามเร็วไหม)?"
  rash_location_primary: "ตำแหน่งหลักของผื่นอยู่บริเวณใดคะ (ใบหน้า/ลำตัว/แขน/ขา/รอบตา/อวัยวะเพศ)?"
  rash_extent: "ผื่นเป็นจุดเดียว หลายจุด หรือทั่วร่างคะ?"
  associated: "มีอาการร่วมใดบ้างคะ (คัน/แสบเจ็บ/มีไข้/บวมหน้า-ลิ้น/มีหนองไหล)?"
  duration: "ผื่นเริ่มมานานเท่าไรแล้วคะ?"
  suspected_triggers: "สงสัยว่าเกิดจากสิ่งกระตุ้นใด (เช่น โลชั่น/สบู่/ผงซักฟอก/อาหาร/ยาสระผม)?"
  vulnerable_groups: "เข้ากลุ่มเสี่ยงไหมคะ (ทารก/ตั้งครรภ์/กดภูมิ/เบาหวาน)?"
  self_care_tried_optional: "ได้ลองดูแลใดแล้วบ้างคะ (ประคบเย็น/มอยส์เจอไรเซอร์/งดผลิตภัณฑ์ที่สงสัย)?"
